### ISSUE TITLE
support unix domain sockets

### ISSUE THREAD

**Issue by Hendrik-H** [IBM/gWhisper#90]
**Is your feature request related to a problem? Please describe.**
I'm developing a gRPC service that is running on a Unix Domain Socket. It would be nice to be able to use gWhisper as a test client.

**Describe the solution you'd like**
The c++ gRPC implementation supports UDS already: https://grpc.github.io/grpc/cpp/md_doc_naming.html
I believe all that is required is to fix a check somewhere in the code that requires `IP:port`.

**Describe alternatives you've considered**
Write an alternative test client.

**Describe why you think this feature is useful for gWhisper users**
Unix Domain Sockets are supported by pretty much all gRPC frameworks.

**Comment by rainerschoe** [comment]
HI, this is a good idea. We also play with the idea of using unix domain sockets in the future.
Will see when I can invest some time on this.

**Comment by rainerschoe** [comment]
Started digging into this. Unfortunately it turned out to be more complex than a one-line change due to gRPC default ports having changed since start of gWhisper development:

gWhisper constructs the host URI from explicitly parsed [ hostname | IPv4 | IPv6 ] + port
if port is not given, 50051 is used (Whis was gRPC default port some years ago).

I changed this to directly parse the host URI (without parsing the components explicitly) this works now also for unix domain sockets.
However the gRPC default port if none is given is now 443 for TCP connections. This would break backwards compatibility of gWhisper.
I cannot find a way to change gRPC default port globally on client side other than modifying the given string URI.

This means I cannot parse URI as plain string, but need to parse it semantically examining all components to determine if it is needed to add a port or not.
This also means I need to have explicit awareness on gWhisper side of unix domain socket URIs (in order to distinguish them from TCP) and cannot just use "pass-through" :(

**Comment by rainerschoe** [comment]
@Hendrik-H see referenced PR. If you wand you could test this against a domain socket server (I do not have a test server set up like this)

In current impl. both `unix:` and `unix-abstract:` prefixes are supported. I do not plan to support the `unix://` prefix as it is redundant and confusing since there will be three slashes in any usage i.e. `unix:///...`
Additionally the `dns:` `ipv4:` and `ipv6:` prefixes should now also be supported. With default TCP port set to 50051 if omitted.

Unfortunately due to a bug in completion there are no tab completion suggestions for the TCP based prefixes (presumably related to `dns:` prefix being optional). But parsing those prefixes should works anyways.

**Comment by Hendrik-H** [comment]
thanks, I will try it out on monday and report back

**Comment by Hendrik-H** [comment]
Hi @rainerschoe , works great, thanks a lot for the quick implementation!
